# Generated by Django 5.0.4 on 2024-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_address',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
