# Generated by Django 5.0.4 on 2024-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_user_user_name_user_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
